# primary environment 

name: gsnn-lib

channels: 
    - pytorch 
    - nvidia 
    - pyg
    - conda-forge
    - mcs07
    - defaults 

dependencies:
    - python=3.12
    - matplotlib
    - pubchempy
    - pyg
    - pytorch
    - pytorch-cuda
    - seaborn
    - scikit-learn
    - h5py
    - scipy
    - tensorboard
    - shapely
    - statsmodels
    - rdkit
    - shap
    - pip
    - pip:
        - tensorboardX
        - ipykernel
        - umap-learn
        - biopython
        - obonet
        - omnipath 
        - adjustText
        - torch-sparse 
        - torch-scatter
        - scperturb
        - pykeops
        - geomloss
