# primary environment 

name: gsnn-lib

channels: 
    - pytorch 
    - nvidia 
    - pyg
    - conda-forge
    - mcs07
    - defaults 

dependencies:
    - python
    - matplotlib
    - pubchempy
    - pyg
    - pytorch
    - pytorch-cuda
    - seaborn
    - scikit-learn
    - h5py
    - scipy
    - tensorboard
    - numpy==1.26 # omnipath not compatible with 2+
    - omnipath
    - torch-scatter
    - shapely
    - statsmodels
    - rdkit
    - shap
    - pip
    - pip:
        - tensorboardX
        - ipykernel
        - umap-learn
        - biopython
        - torch-sparse
        - obonet
        - adjustText
        - scperturb
        - pykeops
        - geomloss
